### ISSUE TITLE
"New user joined" notification is annoying and weird

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#609] opened 2022-06-14 14:23 UTC
We added a "new user joined" notification but it's a bit weird. It can be spoofed, it gets lost in the list of other messages, and it's not clear.

Propose the simplest possible solution and let's fix it.

**Comment by siepra** [comment] 2022-06-14 14:32
Duplicate of #607

**Closed** 2022-06-14 14:32 UTC

**Comment by holmesworcester** [comment] 2022-06-15 12:41
@siepra can you post the latest design here as screenshots?
