### ISSUE TITLE
Add borders to uploaded image

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/monorepo#594] opened 2022-06-09 09:32 UTC
* similar to slack's borders (?)
* add height restriction

**Comment by holmesworcester** [comment] 2022-06-09 13:41
Cases we should consider:

1. Image is not loaded, only placeholder appears
2. Image is loaded but background is white
3. Image is really tall and wide
4. Image is really tall
5. Image is really wide

Anything else?

**Comment by holmesworcester** [comment] 2022-06-14 14:21
Duplicate of #576

**Closed by holmesworcester** 2022-06-14 14:21 UTC
Labels: needs design
